//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPMDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public Nullable<int> ContributorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string ReceiverRole { get; set; }
    
        public virtual Contributor Contributor { get; set; }
        public virtual Contributor Contributor1 { get; set; }
        public virtual DatTour DatTour { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TourDuLich TourDuLich { get; set; }
    }
}
